/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.thai.demo3.java.admin;

import com.thai.demo3.java.ui.*;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.event.ChangeEvent;
import javax.swing.event.ChangeListener;

/**
 *
 * @author 段晓强
 */
public class ManagerChoose extends javax.swing.JFrame {

    /**
     * Creates new form SendChooseUI
     */
    public ManagerChoose() {
//        this.setUndecorated(true);
//        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        this.setAlwaysOnTop(true);
        this.setResizable(false);
        this.requestFocus();
        this.setLocation(0, 0);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        btn_return = new javax.swing.JButton();
        G01 = new javax.swing.JButton("A1");
        G06 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        btn_screen = new javax.swing.JButton();
        A02 = new javax.swing.JButton();
        G02 = new javax.swing.JButton();
        G04 = new javax.swing.JButton();
        G05 = new javax.swing.JButton();
        D01 = new javax.swing.JButton();
        D03 = new javax.swing.JButton();
        E01 = new javax.swing.JButton();
        E03 = new javax.swing.JButton();
        D02 = new javax.swing.JButton();
        D04 = new javax.swing.JButton();
        D06 = new javax.swing.JButton();
        E02 = new javax.swing.JButton();
        E04 = new javax.swing.JButton();
        H01 = new javax.swing.JButton();
        H02 = new javax.swing.JButton();
        F02 = new javax.swing.JButton();
        F04 = new javax.swing.JButton();
        E06 = new javax.swing.JButton();
        F01 = new javax.swing.JButton();
        F03 = new javax.swing.JButton();
        E05 = new javax.swing.JButton();
        H03 = new javax.swing.JButton();
        F05 = new javax.swing.JButton();
        F06 = new javax.swing.JButton();
        A04 = new javax.swing.JButton();
        A06 = new javax.swing.JButton();
        B02 = new javax.swing.JButton();
        A01 = new javax.swing.JButton();
        A03 = new javax.swing.JButton();
        A05 = new javax.swing.JButton();
        B03 = new javax.swing.JButton();
        B05 = new javax.swing.JButton();
        C01 = new javax.swing.JButton();
        C03 = new javax.swing.JButton();
        B06 = new javax.swing.JButton();
        C02 = new javax.swing.JButton();
        C04 = new javax.swing.JButton();
        C05 = new javax.swing.JButton();
        C06 = new javax.swing.JButton();
        G03 = new javax.swing.JButton();
        lab_choose = new javax.swing.JLabel();
        D05 = new javax.swing.JButton();
        B01 = new javax.swing.JButton();
        B04 = new javax.swing.JButton();
        btn_open = new javax.swing.JButton();
        btn_check = new javax.swing.JButton();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        statusImg = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        delNum = new javax.swing.JLabel();
        lab_text = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(251, 205, 57));

        btn_return.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/thai/demo3/java/resources/return.png"))); // NOI18N
        btn_return.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_returnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_return, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(646, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(btn_return, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        G01.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/thai/demo3/java/resources/box.png"))); // NOI18N
        this.checkWhichKey();
        G01.setText("A1");
        G01.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                G01ActionPerformed(evt);
            }
        });

        G06.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/thai/demo3/java/resources/box.png"))); // NOI18N
        G06.setText("F1");
        G06.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                G06ActionPerformed(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(255, 96, 10));

        btn_screen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/thai/demo3/java/resources/screen.png"))); // NOI18N
        btn_screen.setText("jButton2");
        btn_screen.setFocusPainted(false);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_screen, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(btn_screen, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(352, Short.MAX_VALUE))
        );

        A02.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/thai/demo3/java/resources/box.png"))); // NOI18N
        A02.setText("jButton20");
        A02.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                A02ActionPerformed(evt);
            }
        });

        G02.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/thai/demo3/java/resources/box.png"))); // NOI18N
        G02.setText("B1");
        G02.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                G02ActionPerformed(evt);
            }
        });

        G04.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/thai/demo3/java/resources/box.png"))); // NOI18N
        G04.setText("D1");
        G04.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                G04ActionPerformed(evt);
            }
        });

        G05.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/thai/demo3/java/resources/box.png"))); // NOI18N
        G05.setText("E1");
        G05.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                G05ActionPerformed(evt);
            }
        });

        D01.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/thai/demo3/java/resources/box.png"))); // NOI18N
        D01.setText("jButton20");
        D01.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                D01ActionPerformed(evt);
            }
        });

        D03.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/thai/demo3/java/resources/box.png"))); // NOI18N
        D03.setText("jButton20");
        D03.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                D03ActionPerformed(evt);
            }
        });

        E01.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/thai/demo3/java/resources/box.png"))); // NOI18N
        E01.setText("jButton20");
        E01.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                E01ActionPerformed(evt);
            }
        });

        E03.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/thai/demo3/java/resources/box.png"))); // NOI18N
        E03.setText("jButton20");
        E03.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                E03ActionPerformed(evt);
            }
        });

        D02.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/thai/demo3/java/resources/box.png"))); // NOI18N
        D02.setText("jButton20");
        D02.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                D02ActionPerformed(evt);
            }
        });

        D04.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/thai/demo3/java/resources/box.png"))); // NOI18N
        D04.setText("jButton20");
        D04.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                D04ActionPerformed(evt);
            }
        });

        D06.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/thai/demo3/java/resources/box.png"))); // NOI18N
        D06.setText("jButton20");
        D06.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                D06ActionPerformed(evt);
            }
        });

        E02.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/thai/demo3/java/resources/box.png"))); // NOI18N
        E02.setText("jButton20");
        E02.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                E02ActionPerformed(evt);
            }
        });

        E04.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/thai/demo3/java/resources/box.png"))); // NOI18N
        E04.setText("jButton20");
        E04.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                E04ActionPerformed(evt);
            }
        });

        H01.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/thai/demo3/java/resources/box.png"))); // NOI18N
        H01.setText("G1");
        H01.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                H01ActionPerformed(evt);
            }
        });

        H02.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/thai/demo3/java/resources/box.png"))); // NOI18N
        H02.setText("H1");
        H02.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                H02ActionPerformed(evt);
            }
        });

        F02.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/thai/demo3/java/resources/box.png"))); // NOI18N
        F02.setText("jButton20");
        F02.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                F02ActionPerformed(evt);
            }
        });

        F04.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/thai/demo3/java/resources/box.png"))); // NOI18N
        F04.setText("jButton20");
        F04.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                F04ActionPerformed(evt);
            }
        });

        E06.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/thai/demo3/java/resources/box.png"))); // NOI18N
        E06.setText("jButton20");
        E06.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                E06ActionPerformed(evt);
            }
        });

        F01.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/thai/demo3/java/resources/box.png"))); // NOI18N
        F01.setText("jButton20");
        F01.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                F01ActionPerformed(evt);
            }
        });

        F03.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/thai/demo3/java/resources/box.png"))); // NOI18N
        F03.setText("jButton20");
        F03.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                F03ActionPerformed(evt);
            }
        });

        E05.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/thai/demo3/java/resources/box.png"))); // NOI18N
        E05.setText("jButton20");
        E05.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                E05ActionPerformed(evt);
            }
        });

        H03.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/thai/demo3/java/resources/box.png"))); // NOI18N
        H03.setText("I1");
        H03.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                H03ActionPerformed(evt);
            }
        });

        F05.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/thai/demo3/java/resources/box.png"))); // NOI18N
        F05.setText("jButton20");
        F05.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                F05ActionPerformed(evt);
            }
        });

        F06.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/thai/demo3/java/resources/box.png"))); // NOI18N
        F06.setText("jButton20");
        F06.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                F06ActionPerformed(evt);
            }
        });

        A04.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/thai/demo3/java/resources/box.png"))); // NOI18N
        A04.setText("jButton20");
        A04.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                A04ActionPerformed(evt);
            }
        });

        A06.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/thai/demo3/java/resources/box.png"))); // NOI18N
        A06.setText("jButton20");
        A06.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                A06ActionPerformed(evt);
            }
        });

        B02.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/thai/demo3/java/resources/box.png"))); // NOI18N
        B02.setText("jButton20");
        B02.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B02ActionPerformed(evt);
            }
        });

        A01.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/thai/demo3/java/resources/box.png"))); // NOI18N
        A01.setText("jButton20");
        A01.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                A01ActionPerformed(evt);
            }
        });

        A03.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/thai/demo3/java/resources/box.png"))); // NOI18N
        A03.setText("jButton20");
        A03.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                A03ActionPerformed(evt);
            }
        });

        A05.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/thai/demo3/java/resources/box.png"))); // NOI18N
        A05.setText("jButton20");
        A05.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                A05ActionPerformed(evt);
            }
        });

        B03.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/thai/demo3/java/resources/box.png"))); // NOI18N
        B03.setText("jButton20");
        B03.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B03ActionPerformed(evt);
            }
        });

        B05.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/thai/demo3/java/resources/box.png"))); // NOI18N
        B05.setText("jButton20");
        B05.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B05ActionPerformed(evt);
            }
        });

        C01.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/thai/demo3/java/resources/box.png"))); // NOI18N
        C01.setText("jButton20");
        C01.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                C01ActionPerformed(evt);
            }
        });

        C03.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/thai/demo3/java/resources/box.png"))); // NOI18N
        C03.setText("jButton20");
        C03.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                C03ActionPerformed(evt);
            }
        });

        B06.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/thai/demo3/java/resources/box.png"))); // NOI18N
        B06.setText("jButton20");
        B06.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B06ActionPerformed(evt);
            }
        });

        C02.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/thai/demo3/java/resources/box.png"))); // NOI18N
        C02.setText("jButton20");
        C02.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                C02ActionPerformed(evt);
            }
        });

        C04.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/thai/demo3/java/resources/box.png"))); // NOI18N
        C04.setText("jButton20");
        C04.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                C04ActionPerformed(evt);
            }
        });

        C05.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/thai/demo3/java/resources/box.png"))); // NOI18N
        C05.setText("jButton20");
        C05.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                C05ActionPerformed(evt);
            }
        });

        C06.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/thai/demo3/java/resources/box.png"))); // NOI18N
        C06.setText("jButton20");
        C06.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                C06ActionPerformed(evt);
            }
        });

        G03.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/thai/demo3/java/resources/box.png"))); // NOI18N
        G03.setText("C1");
        G03.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                G03ActionPerformed(evt);
            }
        });

        lab_choose.setFont(new java.awt.Font("微软雅黑", 0, 64)); // NOI18N
        lab_choose.setText("请点选快递柜");

        D05.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/thai/demo3/java/resources/box.png"))); // NOI18N
        D05.setText("jButton20");
        D05.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                D05ActionPerformed(evt);
            }
        });

        B01.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/thai/demo3/java/resources/box.png"))); // NOI18N
        B01.setText("jButton20");
        B01.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B01ActionPerformed(evt);
            }
        });

        B04.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/thai/demo3/java/resources/box.png"))); // NOI18N
        B04.setText("jButton20");
        B04.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B04ActionPerformed(evt);
            }
        });

        btn_open.setVisible(false);
        btn_open.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/thai/demo3/java/resources/opendoor.png"))); // NOI18N
        btn_open.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_openActionPerformed(evt);
            }
        });

        btn_check.setVisible(false);
        btn_check.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/thai/demo3/java/resources/checkbox.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(G04, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(G05, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(G03, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(H03, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(H02, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(H01, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(D03, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(E01, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(F03, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                                        .addComponent(F01, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                                        .addComponent(E05, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                        .addComponent(E03, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(F05, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(D05, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(D06, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(D04, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(E02, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(E04, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(E06, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(F02, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(F04, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(F06, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(G06, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                    .addComponent(G02, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                    .addComponent(G01, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(D01, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(D02, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(8, 8, 8)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(A05, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(A03, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(B03, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(B05, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(C01, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(C03, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(C05, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(A01, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(B01, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(B02, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(A06, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(A04, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(B06, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(C02, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(C04, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(C06, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(A02, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(B04, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lab_choose)
                        .addGap(182, 182, 182))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_open, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(btn_check, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(155, 155, 155))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addComponent(lab_choose)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 164, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_open, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_check, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(68, 68, 68)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(A01, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(A02, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(A03, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(A05, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(52, 52, 52)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(B03, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(B04, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(B05, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(C01, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(C03, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(C05, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(A04, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(A06, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(B02, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(B01, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(52, 52, 52)
                            .addComponent(B06, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(C02, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(C04, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(C06, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(46, 46, 46)
                            .addComponent(G02, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(G01, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(D01, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(D02, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(190, 190, 190)
                                    .addComponent(G06, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(6, 6, 6)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(D03, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(G03, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(E01, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(G04, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(E03, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(G05, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGap(70, 70, 70)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                    .addGap(128, 128, 128)
                                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(F05, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(H03, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                    .addGap(64, 64, 64)
                                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(F03, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(H02, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addGap(184, 184, 184)
                                            .addComponent(E05, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addGap(248, 248, 248)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(F01, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(H01, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(D04, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(D06, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(D05, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(E02, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(E04, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(70, 70, 70)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(128, 128, 128)
                                        .addComponent(F06, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(64, 64, 64)
                                        .addComponent(F04, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(184, 184, 184)
                                .addComponent(E06, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(248, 248, 248)
                                .addComponent(F02, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );

        statusImg.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        statusImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/thai/demo3/java/resources/yes.png"))); // NOI18N
        statusImg.setText("jLabel1");

        delNum.setFont(new java.awt.Font("微软雅黑", 0, 32)); // NOI18N
        delNum.setText("C2");

        lab_text.setFont(new java.awt.Font("微软雅黑", 0, 32)); // NOI18N
        lab_text.setText("柜门已打开，请检查后关闭柜门");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 748, Short.MAX_VALUE)
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(delNum)
                    .addContainerGap(698, Short.MAX_VALUE)))
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                    .addContainerGap(290, Short.MAX_VALUE)
                    .addComponent(lab_text)
                    .addContainerGap()))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 72, Short.MAX_VALUE)
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addGap(14, 14, 14)
                    .addComponent(delNum)
                    .addContainerGap(15, Short.MAX_VALUE)))
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addGap(14, 14, 14)
                    .addComponent(lab_text)
                    .addContainerGap(15, Short.MAX_VALUE)))
        );

        jLayeredPane1.setLayer(statusImg, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jPanel4, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 768, Short.MAX_VALUE)
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jLayeredPane1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(statusImg, javax.swing.GroupLayout.DEFAULT_SIZE, 748, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jLayeredPane1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 438, Short.MAX_VALUE)
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jLayeredPane1Layout.createSequentialGroup()
                    .addComponent(statusImg)
                    .addGap(0, 325, Short.MAX_VALUE)))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane1Layout.createSequentialGroup()
                    .addContainerGap(167, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(199, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jLayeredPane1))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(108, Short.MAX_VALUE)
                    .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(563, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void C03ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_C03ActionPerformed
        // TODO add your handling code here:
        lab_choose.setVisible(false);
        btn_open.setVisible(true);
        btn_check.setVisible(true);
        C03.setIcon(new ImageIcon(getClass().getResource("/com/thai/demo3/java/resources/choose_2.png")));
    }//GEN-LAST:event_C03ActionPerformed

    private void A03ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_A03ActionPerformed
        // TODO add your handling code here:
        lab_choose.setVisible(false);
        btn_open.setVisible(true);
        btn_check.setVisible(true);
        A03.setIcon(new ImageIcon(getClass().getResource("/com/thai/demo3/java/resources/choose_3.png")));
    }//GEN-LAST:event_A03ActionPerformed

    private void A04ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_A04ActionPerformed
        // TODO add your handling code here:
       lab_choose.setVisible(false);
        btn_open.setVisible(true);
        btn_check.setVisible(true);
        A04.setIcon(new ImageIcon(getClass().getResource("/com/thai/demo3/java/resources/choose_3.png")));
    }//GEN-LAST:event_A04ActionPerformed

    private void E02ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_E02ActionPerformed
        // TODO add your handling code here:
       lab_choose.setVisible(false);
        btn_open.setVisible(true);
        btn_check.setVisible(true);
        E02.setIcon(new ImageIcon(getClass().getResource("/com/thai/demo3/java/resources/choose.png")));
    }//GEN-LAST:event_E02ActionPerformed

    private void G01ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_G01ActionPerformed
        // TODO add your handling code here:
        G01.setActionCommand("DXQ");
        lab_choose.setVisible(false);
        btn_open.setVisible(true);
        btn_check.setVisible(true);
        G01.setIcon(new ImageIcon(getClass().getResource("/com/thai/demo3/java/resources/choose.png")));
    }//GEN-LAST:event_G01ActionPerformed

    private void btn_returnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_returnActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_btn_returnActionPerformed

    private void H01ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_H01ActionPerformed
        // TODO add your handling code here:
        lab_choose.setVisible(false);
        btn_open.setVisible(true);
        btn_check.setVisible(true);
        H01.setIcon(new ImageIcon(getClass().getResource("/com/thai/demo3/java/resources/choose.png")));
    }//GEN-LAST:event_H01ActionPerformed

    private void G02ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_G02ActionPerformed
        // TODO add your handling code here:
        lab_choose.setVisible(false);
        btn_open.setVisible(true);
        btn_check.setVisible(true);
        G02.setIcon(new ImageIcon(getClass().getResource("/com/thai/demo3/java/resources/choose.png")));
    }//GEN-LAST:event_G02ActionPerformed

    private void G03ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_G03ActionPerformed
        // TODO add your handling code here:
        lab_choose.setVisible(false);
        btn_open.setVisible(true);
        btn_check.setVisible(true);
        G03.setIcon(new ImageIcon(getClass().getResource("/com/thai/demo3/java/resources/choose.png")));
    }//GEN-LAST:event_G03ActionPerformed

    private void G04ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_G04ActionPerformed
        // TODO add your handling code here:
        lab_choose.setVisible(false);
        btn_open.setVisible(true);
        btn_check.setVisible(true);
        G04.setIcon(new ImageIcon(getClass().getResource("/com/thai/demo3/java/resources/choose.png")));
    }//GEN-LAST:event_G04ActionPerformed

    private void G05ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_G05ActionPerformed
        // TODO add your handling code here:
        lab_choose.setVisible(false);
        btn_open.setVisible(true);
        btn_check.setVisible(true);
        G05.setIcon(new ImageIcon(getClass().getResource("/com/thai/demo3/java/resources/choose.png")));
    }//GEN-LAST:event_G05ActionPerformed

    private void G06ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_G06ActionPerformed
        // TODO add your handling code here:
        lab_choose.setVisible(false);
        btn_open.setVisible(true);
        btn_check.setVisible(true);
        G06.setIcon(new ImageIcon(getClass().getResource("/com/thai/demo3/java/resources/choose_1.png")));
    }//GEN-LAST:event_G06ActionPerformed

    private void H02ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_H02ActionPerformed
        // TODO add your handling code here:
      lab_choose.setVisible(false);
        btn_open.setVisible(true);
        btn_check.setVisible(true);
        H02.setIcon(new ImageIcon(getClass().getResource("/com/thai/demo3/java/resources/choose_1.png")));
    }//GEN-LAST:event_H02ActionPerformed

    private void H03ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_H03ActionPerformed
        // TODO add your handling code here:
        lab_choose.setVisible(false);
        btn_open.setVisible(true);
        btn_check.setVisible(true);
        H03.setIcon(new ImageIcon(getClass().getResource("/com/thai/demo3/java/resources/choose_2.png")));
    }//GEN-LAST:event_H03ActionPerformed

    private void D01ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_D01ActionPerformed
        // TODO add your handling code here:
       lab_choose.setVisible(false);
        btn_open.setVisible(true);
        btn_check.setVisible(true);
        D01.setIcon(new ImageIcon(getClass().getResource("/com/thai/demo3/java/resources/choose.png")));
    }//GEN-LAST:event_D01ActionPerformed

    private void D03ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_D03ActionPerformed
        // TODO add your handling code here:
     lab_choose.setVisible(false);
        btn_open.setVisible(true);
        btn_check.setVisible(true);
        D03.setIcon(new ImageIcon(getClass().getResource("/com/thai/demo3/java/resources/choose.png")));
    }//GEN-LAST:event_D03ActionPerformed

    private void E01ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_E01ActionPerformed
        // TODO add your handling code here:
    lab_choose.setVisible(false);
        btn_open.setVisible(true);
        btn_check.setVisible(true);
        E01.setIcon(new ImageIcon(getClass().getResource("/com/thai/demo3/java/resources/choose.png")));
    }//GEN-LAST:event_E01ActionPerformed

    private void E03ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_E03ActionPerformed
        // TODO add your handling code here:
      lab_choose.setVisible(false);
        btn_open.setVisible(true);
        btn_check.setVisible(true);
        E03.setIcon(new ImageIcon(getClass().getResource("/com/thai/demo3/java/resources/choose.png")));
    }//GEN-LAST:event_E03ActionPerformed

    private void E05ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_E05ActionPerformed
        // TODO add your handling code here:
      lab_choose.setVisible(false);
        btn_open.setVisible(true);
        btn_check.setVisible(true);
        E05.setIcon(new ImageIcon(getClass().getResource("/com/thai/demo3/java/resources/choose_1.png")));
    }//GEN-LAST:event_E05ActionPerformed

    private void F01ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_F01ActionPerformed
        // TODO add your handling code here:
      lab_choose.setVisible(false);
        btn_open.setVisible(true);
        btn_check.setVisible(true);
        F01.setIcon(new ImageIcon(getClass().getResource("/com/thai/demo3/java/resources/choose_1.png")));
    }//GEN-LAST:event_F01ActionPerformed

    private void F03ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_F03ActionPerformed
        // TODO add your handling code here:
        lab_choose.setVisible(false);
        btn_open.setVisible(true);
        btn_check.setVisible(true);
        F03.setIcon(new ImageIcon(getClass().getResource("/com/thai/demo3/java/resources/choose_1.png")));
    }//GEN-LAST:event_F03ActionPerformed

    private void F05ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_F05ActionPerformed
        // TODO add your handling code here:
     lab_choose.setVisible(false);
        btn_open.setVisible(true);
        btn_check.setVisible(true);
        F05.setIcon(new ImageIcon(getClass().getResource("/com/thai/demo3/java/resources/choose_2.png")));
    }//GEN-LAST:event_F05ActionPerformed

    private void D02ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_D02ActionPerformed
        // TODO add your handling code here:
      lab_choose.setVisible(false);
        btn_open.setVisible(true);
        btn_check.setVisible(true);
        D02.setIcon(new ImageIcon(getClass().getResource("/com/thai/demo3/java/resources/choose.png")));
    }//GEN-LAST:event_D02ActionPerformed

    private void D04ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_D04ActionPerformed
        // TODO add your handling code here:
      lab_choose.setVisible(false);
        btn_open.setVisible(true);
        btn_check.setVisible(true);
        D04.setIcon(new ImageIcon(getClass().getResource("/com/thai/demo3/java/resources/choose.png")));
    }//GEN-LAST:event_D04ActionPerformed

    private void D06ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_D06ActionPerformed
        // TODO add your handling code here:
     lab_choose.setVisible(false);
        btn_open.setVisible(true);
        btn_check.setVisible(true);
        D06.setIcon(new ImageIcon(getClass().getResource("/com/thai/demo3/java/resources/choose.png")));
    }//GEN-LAST:event_D06ActionPerformed

    private void E04ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_E04ActionPerformed
        // TODO add your handling code here:
       lab_choose.setVisible(false);
        btn_open.setVisible(true);
        btn_check.setVisible(true);
        E04.setIcon(new ImageIcon(getClass().getResource("/com/thai/demo3/java/resources/choose.png")));
    }//GEN-LAST:event_E04ActionPerformed

    private void E06ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_E06ActionPerformed
        // TODO add your handling code here:
      lab_choose.setVisible(false);
        btn_open.setVisible(true);
        btn_check.setVisible(true);
        E06.setIcon(new ImageIcon(getClass().getResource("/com/thai/demo3/java/resources/choose_1.png")));
    }//GEN-LAST:event_E06ActionPerformed

    private void F02ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_F02ActionPerformed
        // TODO add your handling code here:
       lab_choose.setVisible(false);
        btn_open.setVisible(true);
        btn_check.setVisible(true);
        F02.setIcon(new ImageIcon(getClass().getResource("/com/thai/demo3/java/resources/choose_1.png")));
    }//GEN-LAST:event_F02ActionPerformed

    private void F04ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_F04ActionPerformed
        // TODO add your handling code here:
      lab_choose.setVisible(false);
        btn_open.setVisible(true);
        btn_check.setVisible(true);
        F04.setIcon(new ImageIcon(getClass().getResource("/com/thai/demo3/java/resources/choose_1.png")));
    }//GEN-LAST:event_F04ActionPerformed

    private void F06ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_F06ActionPerformed
        // TODO add your handling code here:
      lab_choose.setVisible(false);
        btn_open.setVisible(true);
        btn_check.setVisible(true);
        F06.setIcon(new ImageIcon(getClass().getResource("/com/thai/demo3/java/resources/choose_2.png")));
    }//GEN-LAST:event_F06ActionPerformed

    private void A01ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_A01ActionPerformed
        // TODO add your handling code here:
        lab_choose.setVisible(false);
        btn_open.setVisible(true);
        btn_check.setVisible(true);
        A01.setIcon(new ImageIcon(getClass().getResource("/com/thai/demo3/java/resources/choose_3.png")));
    }//GEN-LAST:event_A01ActionPerformed

    private void A05ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_A05ActionPerformed
        // TODO add your handling code here:
       lab_choose.setVisible(false);
        btn_open.setVisible(true);
        btn_check.setVisible(true);
        A05.setIcon(new ImageIcon(getClass().getResource("/com/thai/demo3/java/resources/choose_3.png")));
    }//GEN-LAST:event_A05ActionPerformed

    private void B03ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B03ActionPerformed
        // TODO add your handling code here:
      lab_choose.setVisible(false);
        btn_open.setVisible(true);
        btn_check.setVisible(true);
        B03.setIcon(new ImageIcon(getClass().getResource("/com/thai/demo3/java/resources/choose_3.png")));
    }//GEN-LAST:event_B03ActionPerformed

    private void B05ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B05ActionPerformed
        // TODO add your handling code here:
       lab_choose.setVisible(false);
        btn_open.setVisible(true);
        btn_check.setVisible(true);
        B05.setIcon(new ImageIcon(getClass().getResource("/com/thai/demo3/java/resources/choose_2.png")));
    }//GEN-LAST:event_B05ActionPerformed

    private void C01ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_C01ActionPerformed
        // TODO add your handling code here:
       lab_choose.setVisible(false);
        btn_open.setVisible(true);
        btn_check.setVisible(true);
        C01.setIcon(new ImageIcon(getClass().getResource("/com/thai/demo3/java/resources/choose_2.png")));
    }//GEN-LAST:event_C01ActionPerformed

    private void C05ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_C05ActionPerformed
        // TODO add your handling code here:
       lab_choose.setVisible(false);
        btn_open.setVisible(true);
        btn_check.setVisible(true);
        C05.setIcon(new ImageIcon(getClass().getResource("/com/thai/demo3/java/resources/choose_2.png")));
    }//GEN-LAST:event_C05ActionPerformed

    private void A02ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_A02ActionPerformed
        // TODO add your handling code here:
      lab_choose.setVisible(false);
        btn_open.setVisible(true);
        btn_check.setVisible(true);
        A02.setIcon(new ImageIcon(getClass().getResource("/com/thai/demo3/java/resources/choose_3.png")));
    }//GEN-LAST:event_A02ActionPerformed

    private void A06ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_A06ActionPerformed
        // TODO add your handling code here:
       lab_choose.setVisible(false);
        btn_open.setVisible(true);
        btn_check.setVisible(true);
        A06.setIcon(new ImageIcon(getClass().getResource("/com/thai/demo3/java/resources/choose_3.png")));
    }//GEN-LAST:event_A06ActionPerformed

    private void B02ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B02ActionPerformed
        // TODO add your handling code here:
       lab_choose.setVisible(false);
        btn_open.setVisible(true);
        btn_check.setVisible(true);
        B02.setIcon(new ImageIcon(getClass().getResource("/com/thai/demo3/java/resources/choose_3.png")));
    }//GEN-LAST:event_B02ActionPerformed

    private void B06ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B06ActionPerformed
        // TODO add your handling code here:
       lab_choose.setVisible(false);
        btn_open.setVisible(true);
        btn_check.setVisible(true);
        B06.setIcon(new ImageIcon(getClass().getResource("/com/thai/demo3/java/resources/choose_2.png")));
    }//GEN-LAST:event_B06ActionPerformed

    private void C02ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_C02ActionPerformed
        // TODO add your handling code here:
       lab_choose.setVisible(false);
        btn_open.setVisible(true);
        btn_check.setVisible(true);
        C02.setIcon(new ImageIcon(getClass().getResource("/com/thai/demo3/java/resources/choose_2.png")));
    }//GEN-LAST:event_C02ActionPerformed

    private void C04ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_C04ActionPerformed
        // TODO add your handling code here:
      lab_choose.setVisible(false);
        btn_open.setVisible(true);
        btn_check.setVisible(true);
        C04.setIcon(new ImageIcon(getClass().getResource("/com/thai/demo3/java/resources/choose_2.png")));
    }//GEN-LAST:event_C04ActionPerformed

    private void C06ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_C06ActionPerformed
        // TODO add your handling code here:
      lab_choose.setVisible(false);
        btn_open.setVisible(true);
        btn_check.setVisible(true);
        C06.setIcon(new ImageIcon(getClass().getResource("/com/thai/demo3/java/resources/choose_2.png")));
    }//GEN-LAST:event_C06ActionPerformed

    private void D05ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_D05ActionPerformed
        // TODO add your handling code here:
        lab_choose.setVisible(false);
        btn_open.setVisible(true);
        btn_check.setVisible(true);
        D05.setIcon(new ImageIcon(getClass().getResource("/com/thai/demo3/java/resources/choose.png")));
    }//GEN-LAST:event_D05ActionPerformed

    private void B01ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B01ActionPerformed
        // TODO add your handling code here:
        lab_choose.setVisible(false);
        btn_open.setVisible(true);
        btn_check.setVisible(true);
        B01.setIcon(new ImageIcon(getClass().getResource("/com/thai/demo3/java/resources/choose_3.png")));
    }//GEN-LAST:event_B01ActionPerformed

    private void B04ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B04ActionPerformed
        // TODO add your handling code here:
        lab_choose.setVisible(false);
        btn_open.setVisible(true);
        btn_check.setVisible(true);
        B04.setIcon(new ImageIcon(getClass().getResource("/com/thai/demo3/java/resources/choose_3.png")));
    }//GEN-LAST:event_B04ActionPerformed

    private void btn_openActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_openActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_openActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManagerChoose.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManagerChoose.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManagerChoose.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManagerChoose.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManagerChoose().setVisible(true);
            }
        });
    }

    private void checkWhichKey(){
        JButton[] jButtons=new JButton[]{G01,G06,H01,H02,F02,F04,E06,B05,C01,C03,B06,F01,F03,E05,
                            H03,F05,C02,C04,C05,C06,G02,A02,G04,G05,D01,D03,E01,E03,D02,D04,D06,
                            E02,E04,F06,A04,A06,B02,A01,A03,A05,B03,G03,D05,B01,B04};
        for(int i=0;i<jButtons.length;i++){
            if("DXQ".equals(jButtons[i].getActionCommand())){
                jButtons[i].setIcon(new ImageIcon(getClass().getResource("/com/thai/demo3/java/resources/box.png")));
            }
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton A01;
    private javax.swing.JButton A02;
    private javax.swing.JButton A03;
    private javax.swing.JButton A04;
    private javax.swing.JButton A05;
    private javax.swing.JButton A06;
    private javax.swing.JButton B01;
    private javax.swing.JButton B02;
    private javax.swing.JButton B03;
    private javax.swing.JButton B04;
    private javax.swing.JButton B05;
    private javax.swing.JButton B06;
    private javax.swing.JButton C01;
    private javax.swing.JButton C02;
    private javax.swing.JButton C03;
    private javax.swing.JButton C04;
    private javax.swing.JButton C05;
    private javax.swing.JButton C06;
    private javax.swing.JButton D01;
    private javax.swing.JButton D02;
    private javax.swing.JButton D03;
    private javax.swing.JButton D04;
    private javax.swing.JButton D05;
    private javax.swing.JButton D06;
    private javax.swing.JButton E01;
    private javax.swing.JButton E02;
    private javax.swing.JButton E03;
    private javax.swing.JButton E04;
    private javax.swing.JButton E05;
    private javax.swing.JButton E06;
    private javax.swing.JButton F01;
    private javax.swing.JButton F02;
    private javax.swing.JButton F03;
    private javax.swing.JButton F04;
    private javax.swing.JButton F05;
    private javax.swing.JButton F06;
    private javax.swing.JButton G01;
    private javax.swing.JButton G02;
    private javax.swing.JButton G03;
    private javax.swing.JButton G04;
    private javax.swing.JButton G05;
    private javax.swing.JButton G06;
    private javax.swing.JButton H01;
    private javax.swing.JButton H02;
    private javax.swing.JButton H03;
    private javax.swing.JButton btn_check;
    private javax.swing.JButton btn_open;
    private javax.swing.JButton btn_return;
    private javax.swing.JButton btn_screen;
    private javax.swing.JLabel delNum;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel lab_choose;
    private javax.swing.JLabel lab_text;
    private javax.swing.JLabel statusImg;
    // End of variables declaration//GEN-END:variables
}
